## YAML Template.
---
spring:
     # Datasource Configuration
     datasource:
         driverClassName: com.mysql.jdbc.Driver
         jndi-name : sampleDatasource
#         url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DB_NAME:sample1}"
#         username: "${DB_USERNAME:root}"
#         password: "${DB_PASSWORD:1234}"
     jpa:         
         database: MYSQL
         show-sql: true
         hibernate:             
             ddl-auto: create
             naming-strategy: "org.hibernate.cfg.ImprovedNamingStrategy"
             dialect: "org.hibernate.dialect.MySQL5Dialect"  
             